### ISSUE TITLE
Project activity and stability

### ISSUE THREAD

**Issue by brennebeck** [zlx/Gitlab-Hound#8]
Hi,

Is there still work ongoing here? I noticed the recent commits seem to be just bundle updates.

So:
1. Is this being actively used in production anywhere?
2. Is it limited to the languages mentioned in the readme or does it support all of Hound's?

Highly interested in where this stands. 

Thanks!

**Comment by zlx** [comment]
Happy hear from you. I have do not work for it for a long time since I have not any production environment for it now.

Current it only support languages mentioned in the Readme.

If you have any question about it, I can provide help for you. Hope it can help someone.
